stages:
  - "publish"

steps:
  publish:
    title: Publish packages
    stage: "publish"
    type: freestyle
    working_directory: "./<your project></your>"
    arguments:
      image: "node:latest"
      commands:
        - yarn run publish
    when:
      branch:
        only:
          - master
