version: "1.0"
stages:
  - "clone"
  - "release"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  release:
    title: Release new version and add to changelog
    stage: "release"
    type: freestyle
    working_directory: "./${{CF_REPO_NAME}}"
    arguments:
      image: "node:latest"
      commands:
        - SECONDS=0
        - yarn
        - echo "Yarn took $SECONDS"
        # So it doesn't ask for fingerprint
        - mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
        - yarn add netlify-cli @11ty/eleventy
        - yarn run release
        - yarn build
        - yarn run netlify deploy --prod
    environment:
        - CI=true
    when:
      branch:
        only:
          - master