version: "1.0"
stages:
  - "clone"
  - "build"
  - "test"
  - "publish"
steps:
  clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "tolicodes/node-api-toolkit"
    revision: "${{CF_BRANCH}}"
    stage: "clone"
  build:
    title: Build packages
    stage: "build"
    type: freestyle
    working_directory: "./node-api-toolkit"
    arguments:
      image: "node:latest"
      commands:
        - npm i -g lerna
        - yarn
        - lerna bootstrap
  test:
    title: Test packages
    stage: "test"
    type: freestyle
    working_directory: "./node-api-toolkit"
    arguments:
      image: "node:latest"
      commands:
        - npm i -g lerna
        - yarn run test:debug

  integration_test:
    title: Integration Test packages
    stage: "test"
    type: freestyle
    working_directory: "./node-api-toolkit"
    arguments:
      image: "node:latest"
      commands:
        - npm i -g lerna
        - yarn run test:integration:debug
  publish:
    title: Publish packages
    stage: "publish"
    type: freestyle
    working_directory: "./node-api-toolkit"
    arguments:
      image: "node:latest"
      commands:
        - yarn run publish --concurrency 1
    when:
      branch:
        only:
          - master
